substitutions:
  device_name: bedroom-ac
  friendly_name: Bedroom AC


esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

  # future BC7215 component
  # external_components:
  #   - source:
  #       type: local
  #       path: ../components


esp8266:
  board: nodemcuv2


logger:


api:


ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  power_save_mode: none

  ap:
    ssid: "${friendly_name} fallback"
    password: "12345678"


captive_portal:


sensor:

  - platform: dht
    pin: GPIO4
    model: DHT22

    temperature:
      name: "${friendly_name} Temperature"

      id: room_temperature

    humidity:
      name: "${friendly_name} Humidity"

    update_interval: 60s